name: Ideas
description: Please use this issue template if you have an idea or improvement. 
title: "[IDEA REQUEST] <description here>"
labels: [idea]
body:
  - type: textarea
    id: description
    attributes:
      label: Description of idea or improvement. 
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add (multiple) screenshot links (if applicable)
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Any additional context
    validations:
      required: false
  
